Timacarp/vuelta serieactual
DoctaDevs/Tabifit pull request #13
Opened 2020-05-23 14:36 UTC by timacarp

Agregue componente y su js correspondiente

2020-05-26 14:29 UTC, pilichanampe commented on Vuelta-Serie-Actual/vuelta-serie-actual.js
> +class Vueltaserieactual extends HTMLElement {}
Hola Tima! no entiendo por qué tenés dos js, con dos clases de nombre muy similar. El archivo que iría sería el de component.js y este no? En ese caso, si este archivo no sirve más, habría que eliminarlo.

2020-05-26 15:23 UTC, timacarp commented on Vuelta-Serie-Actual/vuelta-serie-actual.js
> +class Vueltaserieactual extends HTMLElement {}
sii se me cargo el que tenia de ejemplo sin querer lo tenia en la carpeta

2020-05-26 19:13 UTC, pilichanampe commented on index.html
> +        <tabifit-vueltaserieactual></tabifit-vueltaserieactual>
Esta línea no debería ir dentro del template de <tabifit-screen>. Me parece que Cris empezó con la cadena del caos xD, porque puso su <tabifit-botonconiconoizquierdo> dentro también, pero hay que recordar que <tabifit-screen> hace referencia solo a la pantalla de "bienvenida", es decir, donde aparece el logo de la app junto al botón "Comenzar". Entonces, sacar la línea de acá y ponerla por fuera del cierre </tabifit-screen>

2020-05-26 19:26 UTC, pilichanampe commented on index.html
> +        <div class="vuelta-contenedor"><slot>
Tiene que ser fácil poder ver a través de la indentación el comienzo y cierre de las etiquetas y, si contienen hijos, que sea fácil reconocer dichos hijos.
Hago este comentario porque el `<slot>`, como tiene hijos, debería estar en una línea solo para él para que se entienda la descendencia y su ascendencia también. Lo mismo pasa en la línea 37, la etiqueta `<slot>` debería tener su propia línea y el cierre de `</div>` estar en la línea 38, para que se lea fácilmente dónde cierra el `<div>` de la línea 34.
Pasaría lo mismo en las líneas 38 y 41.

2020-05-26 20:32 UTC, pilichanampe requested changes
Hola, Tima! Hay un par de cosas que hay que rehacer antes de mergear y otras que tengo ganas de consultarle a Joel en la clase, por eso no las puse en los comentarios.
Saludos!

2020-05-27 21:19 UTC, timacarp commented on index.html
> +        <div class="vuelta-contenedor"><slot>
Si la verdad que con los div flashe un poco porque pense que la vuelta y la serie cambia entonces, lo resolvi poniendole un contenedor, obviamente no tengo idea si esta bien o no jajja estaba explorando.

2020-05-27 22:42 UTC, joelalejandro commented on index.html
> +    </template>
Veamos de generalizar este componente para que funcione tanto para series como para vueltas.

2020-05-31 21:09 UTC, pilichanampe approved these changes
Hola, Tima! ahí pude ver los cambios! Está perfecta ahora la indentación 😃  y el componente se ve más prolijo y genérico 😄

2020-05-31 21:10 UTC, merged